# NOTE: Generated By HttpRunner v4.3.5
# FROM: validate.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class WorkflowValidate(HttpRunner):

    config = Config("basic workflow with httpbin").base_url("${get_httpbin_server()}")

    steps = [
        Step(
            RunRequest("validate response with json path")
            .get("/get")
            .params(**{"a": 1, "b": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.a", "1")
            .assert_equal("body.args.b", "2")
        ),
        Step(
            RunRequest("validate response with python script")
            .get("/get")
            .params(**{"a": 1, "b": 2})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    WorkflowValidate().run()
