# NOTICE: Generated By HttpRunner.
import json
import os
import time

import pytest
from loguru import logger

from httprunner.utils import get_platform, ExtendJSONEncoder


@pytest.fixture(scope="session", autouse=True)
def session_fixture(request):
    """setup and teardown each task"""
    logger.info("start running Workflows ...")

    start_at = time.time()

    yield

    logger.info("task finished, generate task summary for --save-tests")

    summary = {
        "success": True,
        "stat": {
            "Workflows": {"total": 0, "success": 0, "fail": 0},
            "steps": {"total": 0, "failures": 0, "successes": 0},
        },
        "time": {"start_at": start_at, "duration": time.time() - start_at},
        "platform": get_platform(),
        "details": [],
    }

    for item in request.node.items:
        workflow_summary = item.instance.get_summary()
        summary["success"] &= workflow_summary.success

        summary["stat"]["Workflows"]["total"] += 1
        summary["stat"]["steps"]["total"] += len(workflow_summary.step_results)
        if workflow_summary.success:
            summary["stat"]["Workflows"]["success"] += 1
            summary["stat"]["steps"]["successes"] += len(
                workflow_summary.step_results
            )
        else:
            summary["stat"]["Workflows"]["fail"] += 1
            summary["stat"]["steps"]["successes"] += (
                len(workflow_summary.step_results) - 1
            )
            summary["stat"]["steps"]["failures"] += 1

        workflow_summary_json = workflow_summary.dict()
        workflow_summary_json["records"] = workflow_summary_json.pop("step_results")
        summary["details"].append(workflow_summary_json)

    summary_path = r"C:\Users\shahar\Documents\GitHub\httprunner.py\examples\postman_echo\logs\request_methods\hardcode.summary.json"
    summary_dir = os.path.dirname(summary_path)
    os.makedirs(summary_dir, exist_ok=True)

    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, cls=ExtendJSONEncoder)

    logger.info(f"generated task summary: {summary_path}")

