# NOTE: Generated By HttpRunner v4.3.5
# FROM: request_methods\request_parameters.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest


class WorkflowRequestWithParameters(HttpRunner):

    @pytest.mark.parametrize(
        "param",
        [
            {
                "user_agent": "iOS/10.1",
                "username": "test1",
                "password": "111111",
                "app_version": 3.1,
            },
            {
                "user_agent": "iOS/10.2",
                "username": "test2",
                "password": "222222",
                "app_version": 3.0,
            },
        ],
    )
    def run(self, param):
        super().run(param)

    config = (
        Config("request methods workflow: validate with parameters")
        .variables(**{"app_version": "f1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    steps = [
        Step(
            RunRequest("get with params")
            .variables(
                **{
                    "foo1": "$username",
                    "foo2": "$password",
                    "sum_v": "${sum_two(1, $app_version)}",
                }
            )
            .get("/get")
            .params(**{"foo1": "$foo1", "foo2": "$foo2", "sum_v": "$sum_v"})
            .headers(**{"User-Agent": "$user_agent,$app_version"})
            .extract()
            .extractor("body.args.foo2", "session_foo2")
            .validate()
            .assert_equal("status_code", 200)
            .assert_string_equals("body.args.sum_v", "${sum_two(1, $app_version)}")
        ),
    ]


if __name__ == "__main__":
    WorkflowRequestWithParameters().run()
