# NOTE: Generated By HttpRunner v4.3.5
# FROM: request_methods\request_variables.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class WorkflowRequestWithVariables(HttpRunner):

    config = (
        Config("request methods workflow with variables")
        .variables(**{"foo1": "workflow_config_bar1", "foo2": "workflow_config_bar2"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    steps = [
        Step(
            RunRequest("get with params")
            .variables(**{"foo1": "bar11", "foo2": "bar21"})
            .get("/get")
            .params(**{"foo1": "$foo1", "foo2": "$foo2"})
            .headers(**{"User-Agent": "HttpRunner/3.0"})
            .extract()
            .extractor("body.args.foo2", "foo3")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.foo1", "bar11")
            .assert_equal("body.args.foo2", "bar21")
        ),
        Step(
            RunRequest("post raw text")
            .variables(**{"foo1": "bar12", "foo3": "bar32"})
            .post("/post")
            .headers(
                **{"User-Agent": "HttpRunner/3.0", "Content-Type": "text/plain"}
            )
            .data(
                "This is expected to be sent back as part of response body: $foo1-$foo2-$foo3."
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                "body.data",
                "This is expected to be sent back as part of response body: bar12-workflow_config_bar2-bar32.",
            )
        ),
        Step(
            RunRequest("post form data")
            .variables(**{"foo2": "bar23"})
            .post("/post")
            .headers(
                **{
                    "User-Agent": "HttpRunner/3.0",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .data("foo1=$foo1&foo2=$foo2&foo3=$foo3")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.form.foo1", "workflow_config_bar1")
            .assert_equal("body.form.foo2", "bar23")
            .assert_equal("body.form.foo3", "bar21")
        ),
        Step(
            RunRequest("post form data using json")
            .variables(
                **{
                    "foo2": "bar23",
                    "jsondata": {"foo1": "$foo1", "foo2": "$foo2", "foo3": "$foo3"},
                }
            )
            .post("/post")
            .headers(
                **{"User-Agent": "HttpRunner/3.0", "Content-Type": "application/json"}
            )
            .json("$jsondata")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.data.foo1", "workflow_config_bar1")
            .assert_equal("body.data.foo2", "bar23")
            .assert_equal("body.data.foo3", "bar21")
        ),
    ]


if __name__ == "__main__":
    WorkflowRequestWithVariables().run()
