# NOTE: Generated By HttpRunner v4.3.5
# FROM: request_methods\request_workflow_reference.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunWorkflow

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from request_methods.request_with_functions_test import (
    WorkflowRequestWithFunctions as RequestWithFunctions,
)


class WorkflowRequestWithWorkflowReference(HttpRunner):

    config = (
        Config("request methods workflow: reference workflow")
        .variables(
            **{
                "foo1": "suite_config_bar1",
                "expect_foo1": "suite_config_bar1",
                "expect_foo2": "config_bar2",
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    steps = [
        Step(
            RunWorkflow("request with functions")
            .variables(
                **{"foo1": "workflow_ref_bar1", "expect_foo1": "workflow_ref_bar1"}
            )
            .setup_hook("${sleep(0.1)}")
            .call(RequestWithFunctions)
            .teardown_hook("${sleep(0.2)}")
            .export(*["foo3"])
        ),
        Step(
            RunRequest("post form data")
            .variables(**{"foo1": "bar1"})
            .post("/post")
            .headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .data("foo1=$foo1&foo2=$foo3")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.form.foo1", "bar1")
            .assert_equal("body.form.foo2", "bar21")
        ),
    ]


if __name__ == "__main__":
    WorkflowRequestWithWorkflowReference().run()
