# NOTE: Generated By HttpRunner v4.3.5
# FROM: request_methods\validate_variables.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class WorkflowValidateWithVariables(HttpRunner):

    config = (
        Config("request methods workflow: validate with variables")
        .variables(**{"foo1": "session_bar1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    steps = [
        Step(
            RunRequest("get with params")
            .variables(**{"foo1": "bar1", "foo2": "session_bar2"})
            .get("/get")
            .params(**{"foo1": "$foo1", "foo2": "$foo2"})
            .headers(**{"User-Agent": "HttpRunner/3.0"})
            .extract()
            .extractor("body.args.foo2", "session_foo2")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.foo1", "$foo1")
            .assert_equal("body.args.foo2", "$foo2")
        ),
        Step(
            RunRequest("post raw text")
            .variables(**{"foo1": "hello world", "foo3": "$session_foo2"})
            .post("/post")
            .headers(
                **{"User-Agent": "HttpRunner/3.0", "Content-Type": "text/plain"}
            )
            .data(
                "This is expected to be sent back as part of response body: $foo1-$foo3."
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                "body.data",
                "This is expected to be sent back as part of response body: hello world-$foo3.",
            )
        ),
        Step(
            RunRequest("post form data")
            .variables(**{"foo1": "bar1", "foo2": "bar2"})
            .post("/post")
            .headers(
                **{
                    "User-Agent": "HttpRunner/3.0",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .data("foo1=$foo1&foo2=$foo2")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.form.foo1", "$foo1")
            .assert_equal("body.form.foo2", "$foo2")
        ),
    ]


if __name__ == "__main__":
    WorkflowValidateWithVariables().run()
