# NOTE: Generated By HttpRunner v4.3.5
# FROM: request_methods\validate_functions.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class WorkflowValidateWithFunctions(HttpRunner):

    config = (
        Config("request methods workflow: validate with functions")
        .variables(**{"foo1": "session_bar1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    steps = [
        Step(
            RunRequest("get with params")
            .variables(
                **{"foo1": "bar1", "foo2": "session_bar2", "sum_v": "${sum_two(1, 2)}"}
            )
            .get("/get")
            .params(**{"foo1": "$foo1", "foo2": "$foo2", "sum_v": "$sum_v"})
            .headers(**{"User-Agent": "HttpRunner/${get_httprunner_version()}"})
            .extract()
            .extractor("body.args.foo2", "session_foo2")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.sum_v", "3")
        ),
    ]


if __name__ == "__main__":
    WorkflowValidateWithFunctions().run()
